# Generated by Django 6.0.3 on 2026-03-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='tienda/')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tienda',
            },
        ),
        migrations.CreateModel(
            name='CategoriaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('imagen', models.ImageField(upload_to='tienda/categorias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tienda.tienda')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField()),
                ('precio_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_rebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen_1', models.ImageField(upload_to='tienda/productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='tienda/productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='tienda/productos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.categoriatienda')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
    ]
