# Generated by Django 6.0.3 on 2026-03-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_1',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_3',
        ),
    ]
