# Generated by Django 6.0.3 on 2026-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_general', models.TextField(verbose_name='Texto general')),
                ('proyectos_completados', models.PositiveIntegerField(default=0, verbose_name='Proyectos completados')),
                ('anios_experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('clientes_felices', models.PositiveIntegerField(default=0, verbose_name='Clientes felices')),
                ('mision', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('imagen_1', models.ImageField(upload_to='about/', verbose_name='Imagen principal')),
                ('imagen_2', models.ImageField(upload_to='about/', verbose_name='Imagen secundaria')),
            ],
            options={
                'verbose_name': 'Sobre Nosotros',
                'verbose_name_plural': 'Sobre Nosotros',
            },
        ),
    ]
