# Generated by Django 6.0.3 on 2026-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('imagen', models.ImageField(upload_to='team/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['orden'],
            },
        ),
    ]
