# Generated by Django 6.0.3 on 2026-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/', verbose_name='Logo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('horario', models.CharField(max_length=200, verbose_name='Horario de atención')),
                ('copyright', models.CharField(max_length=200, verbose_name='Copyright')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50, verbose_name='Plataforma')),
                ('url', models.URLField(verbose_name='URL')),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono: facebook, instagram, twitter, linkedin, youtube, whatsapp, tiktok', max_length=50, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['orden'],
            },
        ),
    ]
