# Generated by Django 6.0.3 on 2026-03-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='portafolio/')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolio',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('imagen', models.ImageField(upload_to='portafolio/categorias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='portafoleo.portafolio')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField()),
                ('imagen_1', models.ImageField(upload_to='portafolio/locaciones/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='portafolio/locaciones/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='portafolio/locaciones/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaciones', to='portafoleo.categoriaportafolio')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
    ]
